title: Hello, I'm Bibhu Sahoo
description: > # this means to ignore newlines until "baseurl:"
  Artificial Intelligence and Machine Learning enthusiast.
  Seasoned IT professional with strong skills in IT Operations and Service Management.
  I have experience of working in the IT Services industry for the past 14 years.
permalink: ':title/'
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Bibhu Sahoo # add your name
author-img: bibhu.jpg # add your photo
about-author: Data Science and Machine Learning enthusiast. Senior IT professional with all round skills to deliver outstanding results in competitive environments. Always hungry to keep learning. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: 2bibhu # add your Github handle
social-linkedin: https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile&lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_top_card%3BV1arEr98QjWk5li7Ac0b%2BQ%3D%3D # add your Linkedin handle
social-email: 2bibhu@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 3
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
